dind: disable mounting securityfs (experimental)

diff --git a/hack/dind b/hack/dind
--- a/hack/dind
+++ b/hack/dind
@@ -25,12 +25,12 @@ if ! mountpoint -q "$CGROUP"; then
 	}
 fi
 
-if [ -d /sys/kernel/security ] && ! mountpoint -q /sys/kernel/security; then
-	mount -t securityfs none /sys/kernel/security || {
-		echo >&2 'Could not mount /sys/kernel/security.'
-		echo >&2 'AppArmor detection and -privileged mode might break.'
-	}
-fi
+#if [ -d /sys/kernel/security ] && ! mountpoint -q /sys/kernel/security; then
+#	mount -t securityfs none /sys/kernel/security || {
+#		echo >&2 'Could not mount /sys/kernel/security.'
+#		echo >&2 'AppArmor detection and -privileged mode might break.'
+#	}
+#fi
 
 # Mount the cgroup hierarchies exactly as they are in the parent system.
 for HIER in $(cut -d: -f2 /proc/1/cgroup); do
